# Data Integrity Case Workbook

Read case document and complete all tasks in this workbook.

## Group Information

Write group name and all members' name in this cell.

- Group Name:
- Members:

## Import

In [37]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

## Task 1: Load Transaction Data (5 points)
- Load 2020 and 2021 transaction data.
- Combine two years data to one DataFrame `df`.
- Explore `df` a bit. Display a few rows and check basic dataframe information.

In [38]:
df_2020 = pd.read_excel('jinchange_2020.xlsx')
df_2021 = pd.read_excel('jinchange_2021.xlsx')

print('2020 shape:', df_2020.shape)
print('2021 shape:', df_2021.shape)

df = pd.concat([df_2020, df_2021], ignore_index=True)
df['Invoice_Date'] = pd.to_datetime(df['Invoice_Date'], errors='coerce')
df['Payment_Date'] = pd.to_datetime(df['Payment_Date'], errors='coerce')

df.head()
df.info()

2020 shape: (172, 32)
2021 shape: (136, 32)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 32 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Invoice_Number                   308 non-null    object
 1   Trade_Type                       308 non-null    object
 2   Invoice_Date                     255 non-null    datetime64[ns]
 3   Customer_Name                    308 non-null    object
 4   Customer_Email                   308 non-null    object
 5   Customer_Address                 308 non-null    object
 6   Model                            308 non-null    object
 7   Model_Description                308 non-null    object
 8   Quantity_Ton                     308 non-null    float64
 9   Unit_Price_USD                   308 non-null    float64
 10  Unit_Price_RMB                   308 non-null    int64
 11  Total_Receivable_USD             308 non-null    float64
 12  Total_Receivable_RMB             308 non-null    int64
 13  Total_Received_USD               308 non-null    float64
 14  Foreign_Bank_Deduction_USD       308 non-null    float64
 15  Settlement_RMB                   308 non-null    float64
 16  Total_Received_RMB               308 non-null    int64
 17  Payment_Date                     262 non-null    datetime64[ns]
 18  Ocean_Freight_Fee                308 non-null    float64
 19  Port_Charge                      308 non-null    float64
 20  Insurance                        308 non-null    float64
 21  Land_Freight                     308 non-null    float64
 22  Other_Charge                     308 non-null    float64
 23  Courier_Fee                      308 non-null    int64
 24  Handling_Fee                     308 non-null    int64
 25  Supplier_Name                    308 non-null    object
 26  Supplier_Email                   308 non-null    object
 27  Supplier_Address                 308 non-null    object
 28  Purchase_Invoice_Quantity_Ton    308 non-null    float64
 29  Purchase_Invoice_Unit_Price_RMB  308 non-null    float64
 30  Purchase_Invoice_Total_RMB       308 non-null    float64
 31  Sales_Profit                     308 non-null    float64
dtypes: datetime64[ns](2), float64(15), int64(5), object(10)
memory usage: 77.1+ KB

In [39]:
df.info()
df.describe(include='number')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 32 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Invoice_Number                   308 non-null    object
 1   Trade_Type                       308 non-null    object
 2   Invoice_Date                     255 non-null    datetime64[ns]
 3   Customer_Name                    308 non-null    object
 4   Customer_Email                   308 non-null    object
 5   Customer_Address                 308 non-null    object
 6   Model                            308 non-null    object
 7   Model_Description                308 non-null    object
 8   Quantity_Ton                     308 non-null    float64
 9   Unit_Price_USD                   308 non-null    float64
 10  Unit_Price_RMB                   308 non-null    int64
 11  Total_Receivable_USD             308 non-null    float64
 12  Total_Receivable_RMB             308 non-null    int64
 13  Total_Received_USD               308 non-null    float64
 14  Foreign_Bank_Deduction_USD       308 non-null    float64
 15  Settlement_RMB                   308 non-null    float64
 16  Total_Received_RMB               308 non-null    int64
 17  Payment_Date                     262 non-null    datetime64[ns]
 18  Ocean_Freight_Fee                308 non-null    float64
 19  Port_Charge                      308 non-null    float64
 20  Insurance                        308 non-null    float64
 21  Land_Freight                     308 non-null    float64
 22  Other_Charge                     308 non-null    float64
 23  Courier_Fee                      308 non-null    int64
 24  Handling_Fee                     308 non-null    int64
 25  Supplier_Name                    308 non-null    object
 26  Supplier_Email                   308 non-null    object
 27  Supplier_Address                 308 non-null    object
 28  Purchase_Invoice_Quantity_Ton    308 non-null    float64
 29  Purchase_Invoice_Unit_Price_RMB  308 non-null    float64
 30  Purchase_Invoice_Total_RMB       308 non-null    float64
 31  Sales_Profit                     308 non-null    float64
dtypes: datetime64[ns](2), float64(15), int64(5), object(10)
memory usage: 77.1+ KB

,Quantity_Ton,Unit_Price_USD,Unit_Price_RMB,Total_Receivable_USD,Total_Receivable_RMB,Total_Received_USD,Foreign_Bank_Deduction_USD,Settlement_RMB,Total_Received_RMB,Ocean_Freight_Fee,Port_Charge,Insurance,Land_Freight,Other_Charge,Courier_Fee,Handling_Fee,Purchase_Invoice_Quantity_Ton,Purchase_Invoice_Unit_Price_RMB,Purchase_Invoice_Total_RMB,Sales_Profit
count,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000
mean,9.403685,2478.907078,5058.993506,14165.623656,7147.548701,14896.238636,30.832154,98154.486956,7309.983766,6481.592435,2133.564221,83.111461,1102.029318,1175.717273,87.084416,20.142857,9.403685,15730.580812,77735.912838,16645.315904
std,11.101801,5192.660051,12468.737713,15415.515752,25354.724185,17402.532798,62.030079,112999.668552,26714.194044,16813.748988,2289.577739,128.968802,3586.883231,4415.397951,140.644489,97.528509,11.101801,30556.032550,78836.481596,52965.205302
min,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-11929.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,1250.000000,135.000000,-187200.000000
25%,1.150000,770.000000,0.000000,1261.875000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.150000,7100.000000,15622.500000,1073.147500
50%,6.000000,1505.000000,0.000000,9830.000000,0.000000,10337.000000,10.000000,71168.230000,0.000000,0.000000,2204.620000,0.000000,0.000000,0.000000,18.000000,0.000000,6.000000,10530.000000,52334.000000,8180.680000
75%,12.000000,2505.000000,0.000000,22080.000000,0.000000,23703.050000,44.250000,156513.632500,0.000000,4539.780000,3419.250000,130.777500,0.000000,192.500000,145.750000,0.000000,12.000000,13800.000000,126420.000000,26565.132500
max,54.000000,52250.000000,110000.000000,99900.000000,200700.000000,99890.000000,721.000000,637088.470000,200700.000000,145639.350000,12885.000000,669.260000,43746.810000,32400.000000,925.000000,644.000000,54.000000,340000.000000,550800.000000,399416.840000

## Task 2: Create DB Tables (20 points)
- Create a sqlite dabase `jinchang.db`
- Enable foreign key enforcement
- Identify tables and table columns
- Create script to create DB tables:
    - Each table should have an autoincrement primary key
    - Set proper constrains like NOT NULL, UNIQUE etc
- Drop the tables if already exist in the DB
- Run the script to create tables in the DB

In [40]:
conn = sqlite3.connect('jinchang.db')
conn.execute('PRAGMA foreign_keys = ON;')

print('Database Connceted')

Database Connceted

## Create SQL Tables

In [41]:
sql_script = """
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS shipping_handling;
DROP TABLE IF EXISTS purchase_invoices;
DROP TABLE IF EXISTS invoice_items;
DROP TABLE IF EXISTS sales_invoices;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_name TEXT UNIQUE NOT NULL,
    customer_email TEXT,
    customer_address TEXT
);

CREATE TABLE products (
    product_id INTEGER PRIMARY KEY AUTOINCREMENT,
    model TEXT UNIQUE NOT NULL,
    model_description TEXT
);

CREATE TABLE suppliers (
    supplier_id INTEGER PRIMARY KEY AUTOINCREMENT,
    supplier_name TEXT UNIQUE NOT NULL,
    supplier_email TEXT,
    supplier_address TEXT
);

CREATE TABLE sales_invoices (
    invoice_id INTEGER PRIMARY KEY AUTOINCREMENT,
    invoice_number TEXT UNIQUE NOT NULL,
    trade_type TEXT NOT NULL CHECK (trade_type IN ('Export', 'Domestic')),
    invoice_date TEXT,
    customer_id INTEGER NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE invoice_items (
    item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    invoice_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity_ton REAL NOT NULL,
    unit_price_usd REAL DEFAULT 0,
    unit_price_rmb REAL DEFAULT 0,
    total_receivable_usd REAL DEFAULT 0,
    total_receivable_rmb REAL DEFAULT 0,
    FOREIGN KEY (invoice_id) REFERENCES sales_invoices(invoice_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE shipping_handling (
    shipping_id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER UNIQUE NOT NULL,
    ocean_freight_fee REAL DEFAULT 0,
    port_charge REAL DEFAULT 0,
    insurance REAL DEFAULT 0,
    land_freight REAL DEFAULT 0,
    other_charge REAL DEFAULT 0,
    courier_fee REAL DEFAULT 0,
    handling_fee REAL DEFAULT 0,
    FOREIGN KEY (item_id) REFERENCES invoice_items(item_id)
);

CREATE TABLE purchase_invoices (
    purchase_id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER UNIQUE NOT NULL,
    supplier_id INTEGER NOT NULL,
    purchase_quantity_ton REAL NOT NULL,
    purchase_unit_price_rmb REAL DEFAULT 0,
    purchase_total_rmb REAL DEFAULT 0,
    sales_profit REAL DEFAULT 0,
    FOREIGN KEY (item_id) REFERENCES invoice_items(item_id),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

CREATE TABLE payments (
    payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    invoice_id INTEGER NOT NULL,
    payment_date TEXT,
    total_received_usd REAL DEFAULT 0,
    foreign_bank_deduction_usd REAL DEFAULT 0,
    settlement_rmb REAL DEFAULT 0,
    total_received_rmb REAL DEFAULT 0,
    FOREIGN KEY (invoice_id) REFERENCES sales_invoices(invoice_id)
);
"""

conn.executescript(sql_script)

## Task 3: Populate Data (20 points)
- Populate data from the spreadsheets to the DB tables.
- Commit changes to the DB.

In [42]:
df.columns

df_customer = df[['Customer_Name', 'Customer_Email', 'Customer_Address']].drop_duplicates()
df_customer_to_db = df_customer.rename(columns={
    'Customer_Name': 'customer_name',
    'Customer_Email': 'customer_email',
    'Customer_Address': 'customer_address'
})
df_customer_to_db.to_sql('customers', conn, if_exists='append', index=False)

df_customer = pd.read_sql_query('select * from customers', conn)
df_customer.head()

,customer_id,customer_name,customer_email,customer_address
0,1,SummitRidge Group,info@summitridgegrp.com,Salt Lake City UT USA
1,2,ApexNova Chemicals,sales@apexnovachem.com,Edison NJ USA
2,3,Edgeway Systems,contact@edgewaysys.com,Chicago IL USA
3,4,IdeaSpring Group,hello@ideaspringgrp.com,San Mateo CA USA
4,5,ForgeLine Manufacturing,info@forgeline.com,Indianapolis IN USA

In [43]:
df_product = df[['Model', 'Model_Description']].drop_duplicates()
df_product_to_db = df_product.rename(columns={
    'Model': 'model',
    'Model_Description': 'model_description'
})
df_product_to_db.to_sql('products', conn, if_exists='append', index=False)

df_product = pd.read_sql_query('select * from products', conn)
df_product.head()

   product_id    model                                  model_description
0           1  YCB3211  General industrial material with good compatib...
1           2     N774  Reinforcing carbon black for rubber applicatio...
2           3       H1  General industrial material supporting uniform...
3           4     N220  Reinforcing carbon black for rubber applicatio...
4           5     N330  Reinforcing carbon black for rubber applicatio...

In [44]:
df_supplier = df[['Supplier_Name', 'Supplier_Email', 'Supplier_Address']].drop_duplicates()
df_supplier_to_db = df_supplier.rename(columns={
    'Supplier_Name': 'supplier_name',
    'Supplier_Email': 'supplier_email',
    'Supplier_Address': 'supplier_address'
})
df_supplier_to_db.to_sql('suppliers', conn, if_exists='append', index=False)

df_supplier = pd.read_sql_query('select * from suppliers', conn)
df_supplier.head()

,supplier_id,supplier_name,supplier_email,supplier_address
0,1,ZenithRise Chemicals,info@zenithrise.cn,Hangzhou Zhejiang China
1,2,IronRiver Materials,sales@ironrivermat.cn,Hejin Shanxi China
2,3,Hualink Supply Services,contact@hualinksupply.cn,Beijing China
3,4,NestCarbon Industries,info@nestcarbon.cn,Zibo Shandong China
4,5,TriVolt Energy Materials,info@trivoltenergy.cn,Taiyuan Shanxi China

In [45]:
df_invoice = df[['Invoice_Number', 'Trade_Type', 'Invoice_Date', 'Customer_Name']].copy()
df_invoice = df_invoice.sort_values(['Invoice_Number', 'Invoice_Date']).groupby('Invoice_Number', as_index=False).first()
df_invoice['Invoice_Date'] = df_invoice['Invoice_Date'].dt.strftime('%Y-%m-%d')
df_invoice = pd.merge(df_invoice, df_customer[['customer_id', 'customer_name']], left_on='Customer_Name', right_on='customer_name', how='left')

df_invoice_to_db = df_invoice[['Invoice_Number', 'Trade_Type', 'Invoice_Date', 'customer_id']].rename(columns={
    'Invoice_Number': 'invoice_number',
    'Trade_Type': 'trade_type',
    'Invoice_Date': 'invoice_date'
})
df_invoice_to_db.to_sql('sales_invoices', conn, if_exists='append', index=False)

payment_columns = ['Invoice_Number', 'Payment_Date', 'Total_Received_USD', 'Foreign_Bank_Deduction_USD', 'Settlement_RMB', 'Total_Received_RMB']
df_payment = df[payment_columns].copy()

payment_mask = df_payment['Payment_Date'].notna() | df_payment[['Total_Received_USD', 'Foreign_Bank_Deduction_USD', 'Settlement_RMB', 'Total_Received_RMB']].fillna(0).ne(0).any(axis=1)
df_payment = df_payment[payment_mask].drop_duplicates()
df_payment['Payment_Date'] = df_payment['Payment_Date'].dt.strftime('%Y-%m-%d')
df_payment = pd.merge(df_payment, pd.read_sql_query('select invoice_id, invoice_number from sales_invoices', conn), left_on='Invoice_Number', right_on='invoice_number', how='left')

df_payment_to_db = df_payment[['invoice_id', 'Payment_Date', 'Total_Received_USD', 'Foreign_Bank_Deduction_USD', 'Settlement_RMB', 'Total_Received_RMB']].rename(columns={
    'Payment_Date': 'payment_date',
    'Total_Received_USD': 'total_received_usd',
    'Foreign_Bank_Deduction_USD': 'foreign_bank_deduction_usd',
    'Settlement_RMB': 'settlement_rmb',
    'Total_Received_RMB': 'total_received_rmb'
})
df_payment_to_db.to_sql('payments', conn, if_exists='append', index=False)

pd.read_sql_query('select * from sales_invoices limit 5', conn)

   invoice_id invoice_number trade_type invoice_date  customer_id
0           1     20-HCCH001     Export   2020-01-01            1
1           2     20-HCCH002     Export   2020-01-01            2
2           3     20-HCCH003     Export   2020-01-01            2
3           4     20-HCCH004     Export   2020-01-01            3
4           5     20-HCCH005     Export   2020-01-04            4

In [46]:
def insert_line_level_data(df_line_input, conn):
    df_invoice_id = pd.read_sql_query('select invoice_id, invoice_number from sales_invoices', conn)
    df_product_id = pd.read_sql_query('select product_id, model from products', conn)
    df_supplier_id = pd.read_sql_query('select supplier_id, supplier_name from suppliers', conn)

    df_line_ready = pd.merge(df_line_input, df_invoice_id, left_on='Invoice_Number', right_on='invoice_number', how='left')
    df_line_ready = pd.merge(df_line_ready, df_product_id, left_on='Model', right_on='model', how='left')
    df_line_ready = pd.merge(df_line_ready, df_supplier_id, left_on='Supplier_Name', right_on='supplier_name', how='left')

    for row in df_line_ready.itertuples(index=False):
        cursor = conn.execute(
            '''
            INSERT INTO invoice_items (
                invoice_id, product_id, quantity_ton, unit_price_usd,
                unit_price_rmb, total_receivable_usd, total_receivable_rmb
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
            ''',
            (
                int(row.invoice_id), int(row.product_id), float(row.Quantity_Ton),
                float(row.Unit_Price_USD), float(row.Unit_Price_RMB),
                float(row.Total_Receivable_USD), float(row.Total_Receivable_RMB)
            )
        )
        item_id = cursor.lastrowid

        conn.execute(
            '''
            INSERT INTO shipping_handling (
                item_id, ocean_freight_fee, port_charge, insurance,
                land_freight, other_charge, courier_fee, handling_fee
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ''',
            (
                item_id, float(row.Ocean_Freight_Fee), float(row.Port_Charge),
                float(row.Insurance), float(row.Land_Freight), float(row.Other_Charge),
                float(row.Courier_Fee), float(row.Handling_Fee)
            )
        )

        conn.execute(
            '''
            INSERT INTO purchase_invoices (
                item_id, supplier_id, purchase_quantity_ton,
                purchase_unit_price_rmb, purchase_total_rmb, sales_profit
            ) VALUES (?, ?, ?, ?, ?, ?)
            ''',
            (
                item_id, int(row.supplier_id), float(row.Purchase_Invoice_Quantity_Ton),
                float(row.Purchase_Invoice_Unit_Price_RMB),
                float(row.Purchase_Invoice_Total_RMB), float(row.Sales_Profit)
            )
        )

line_columns = [
    'Invoice_Number', 'Model', 'Quantity_Ton', 'Unit_Price_USD', 'Unit_Price_RMB',
    'Total_Receivable_USD', 'Total_Receivable_RMB', 'Ocean_Freight_Fee', 'Port_Charge',
    'Insurance', 'Land_Freight', 'Other_Charge', 'Courier_Fee', 'Handling_Fee',
    'Supplier_Name', 'Purchase_Invoice_Quantity_Ton', 'Purchase_Invoice_Unit_Price_RMB',
    'Purchase_Invoice_Total_RMB', 'Sales_Profit'
]

df_line = df[line_columns].copy()
insert_line_level_data(df_line, conn)

conn.commit()
pd.read_sql_query('select * from invoice_items limit 5', conn)

,item_id,invoice_id,product_id,quantity_ton,unit_price_usd,unit_price_rmb,total_receivable_usd,total_receivable_rmb
0,1,1,1,1.50,2500.0,0.0,3750.0,0.0
1,2,2,2,25.20,940.0,0.0,23688.0,0.0
2,3,3,3,14.00,1620.0,0.0,22680.0,0.0
3,4,4,3,9.24,1100.0,0.0,10164.0,0.0
4,5,5,4,19.80,950.0,0.0,18810.0,0.0

In [47]:
conn.close()

## Task 4: Add New Transaction (20 points)

- Describe the process to add a new sale.
- Record two new sales into the database. The new sales information is in `new_sales.csv`.
- Commit changes and close DB connection.

### Task 4-1: Describe the Process to Add a New Sale
List the steps in this cell:
- Step 1: Connect to `jinchang.db` and enable foreign key enforcement.
- Step 2: Load the new transaction rows from `new_sales.csv` and convert invoice/payment dates to a standard date format.
- Step 3: Insert any new customer, product, and supplier records that do not already exist in the profile tables.
- Step 4: Create one record in `sales_invoice` for each new invoice number, using invoice-level values such as customer, trade type, invoice date, and total payment amounts.
- Step 5: Create one record in `invoice_item` for each row in the file, then add the matching `purchase_invoice` and `shipping_handling` rows for each item.
- Step 6: Insert payment records into `payment_receipt` for rows that contain payment information, commit the transaction, and close the database connection.

In [48]:
conn = sqlite3.connect('jinchang.db')
conn.execute('PRAGMA foreign_keys = ON;')

df_new_sales = pd.read_csv('new_sales.csv')
df_new_sales['Invoice_Date'] = pd.to_datetime(df_new_sales['Invoice_Date'], errors='coerce')
df_new_sales['Payment_Date'] = pd.to_datetime(df_new_sales['Payment_Date'], errors='coerce')
df_new_sales

# Add missing customers
df_new_customer = df_new_sales[['Customer_Name', 'Customer_Email', 'Customer_Address']].drop_duplicates()
existing_customer = pd.read_sql_query('select customer_name from customers', conn)
df_new_customer = df_new_customer[~df_new_customer['Customer_Name'].isin(existing_customer['customer_name'])]
if not df_new_customer.empty:
    df_new_customer.rename(columns={
        'Customer_Name': 'customer_name',
        'Customer_Email': 'customer_email',
        'Customer_Address': 'customer_address'
    }).to_sql('customers', conn, if_exists='append', index=False)

# Add missing products
df_new_product = df_new_sales[['Model', 'Model_Description']].drop_duplicates()
existing_product = pd.read_sql_query('select model from products', conn)
df_new_product = df_new_product[~df_new_product['Model'].isin(existing_product['model'])]
if not df_new_product.empty:
    df_new_product.rename(columns={
        'Model': 'model',
        'Model_Description': 'model_description'
    }).to_sql('products', conn, if_exists='append', index=False)

# Add missing suppliers
df_new_supplier = df_new_sales[['Supplier_Name', 'Supplier_Email', 'Supplier_Address']].drop_duplicates()
existing_supplier = pd.read_sql_query('select supplier_name from suppliers', conn)
df_new_supplier = df_new_supplier[~df_new_supplier['Supplier_Name'].isin(existing_supplier['supplier_name'])]
if not df_new_supplier.empty:
    df_new_supplier.rename(columns={
        'Supplier_Name': 'supplier_name',
        'Supplier_Email': 'supplier_email',
        'Supplier_Address': 'supplier_address'
    }).to_sql('suppliers', conn, if_exists='append', index=False)

# Add new invoice headers
df_new_invoice = df_new_sales[['Invoice_Number', 'Trade_Type', 'Invoice_Date', 'Customer_Name']].copy()
df_new_invoice = df_new_invoice.sort_values(['Invoice_Number', 'Invoice_Date']).groupby('Invoice_Number', as_index=False).first()
df_new_invoice = pd.merge(df_new_invoice, pd.read_sql_query('select customer_id, customer_name from customers', conn), left_on='Customer_Name', right_on='customer_name', how='left')
df_new_invoice['Invoice_Date'] = df_new_invoice['Invoice_Date'].dt.strftime('%Y-%m-%d')
df_new_invoice_to_db = df_new_invoice[['Invoice_Number', 'Trade_Type', 'Invoice_Date', 'customer_id']].rename(columns={
    'Invoice_Number': 'invoice_number',
    'Trade_Type': 'trade_type',
    'Invoice_Date': 'invoice_date'
})
df_new_invoice_to_db.to_sql('sales_invoices', conn, if_exists='append', index=False)

# Add payment records
df_new_payment = df_new_sales[payment_columns].copy()
payment_mask = df_new_payment['Payment_Date'].notna() | df_new_payment[['Total_Received_USD', 'Foreign_Bank_Deduction_USD', 'Settlement_RMB', 'Total_Received_RMB']].fillna(0).ne(0).any(axis=1)
df_new_payment = df_new_payment[payment_mask].drop_duplicates()
df_new_payment['Payment_Date'] = df_new_payment['Payment_Date'].dt.strftime('%Y-%m-%d')
df_new_payment = pd.merge(df_new_payment, pd.read_sql_query('select invoice_id, invoice_number from sales_invoices', conn), left_on='Invoice_Number', right_on='invoice_number', how='left')
df_new_payment_to_db = df_new_payment[['invoice_id', 'Payment_Date', 'Total_Received_USD', 'Foreign_Bank_Deduction_USD', 'Settlement_RMB', 'Total_Received_RMB']].rename(columns={
    'Payment_Date': 'payment_date',
    'Total_Received_USD': 'total_received_usd',
    'Foreign_Bank_Deduction_USD': 'foreign_bank_deduction_usd',
    'Settlement_RMB': 'settlement_rmb',
    'Total_Received_RMB': 'total_received_rmb'
})
df_new_payment_to_db.to_sql('payments', conn, if_exists='append', index=False)

# Add line-level records
df_new_line = df_new_sales[line_columns].copy()
insert_line_level_data(df_new_line, conn)
conn.commit()

### Task 4-2: Record New Sales to DB
- Record two new sales in `new_sales.csv` to DB
- Commite changes to DB

In [49]:
pd.read_sql_query("select * from sales_invoices where invoice_number in ('25-HCCH001', '25-HCCH002')", conn)
conn.commit()

## Task 5: Data Analysis (15 points)

- Connect to Jinchang Database
- Load data to DataFrames
- Complete following analysis:
    -  Top 5 International Customers by Sales
    -  Top 5 Products by Quantity Sold
    -  Top 5 Suppliers by Total Purchasing Amount
- Close the DB connection.

In [50]:
conn.close()
conn = sqlite3.connect('jinchang.db')

df_customer = pd.read_sql_query('select * from customers', conn)
df_product = pd.read_sql_query('select * from products', conn)
df_supplier = pd.read_sql_query('select * from suppliers', conn)
df_invoice = pd.read_sql_query('select * from sales_invoices', conn)
df_item = pd.read_sql_query('select * from invoice_items', conn)
df_purchase = pd.read_sql_query('select * from purchase_invoices', conn)
df_payment = pd.read_sql_query('select * from payments', conn)

df_invoice_all = pd.merge(df_invoice, df_customer, on='customer_id', how='left')
df_payment_all = pd.merge(df_payment, df_invoice_all, on='invoice_id', how='left')

df_item_all = pd.merge(df_item, df_product, on='product_id', how='left')
df_item_all = pd.merge(df_item_all, df_purchase, on='item_id', how='left')
df_item_all = pd.merge(df_item_all, df_supplier, on='supplier_id', how='left')

### Analysis #1: Top 5 International Customers by Sales
- Rank international customers by total sales (`settlement_rmb`).
- List top 5 customer names and total settlement in RMB.

In [51]:
df_payment_all[df_payment_all['trade_type'] == 'Export'].groupby('customer_name', as_index=False)['settlement_rmb'].sum().sort_values('settlement_rmb', ascending=False).head(5).rename(columns={'settlement_rmb': 'total_settlement_rmb'})

              customer_name  total_settlement_rmb
22  FusionCore Technologies          3.917480e+06
38         Nexera Chemicals          3.663708e+06
57          StrataChem Asia          1.919302e+06
29         IdeaSpring Group          1.661022e+06
18              ExactaForge          1.562515e+06

### Analysis #2: Top 5 Products by Quantity Sold
- Rank products by quantity sold.
- List top 5 product models and total quantity sold.

In [52]:
df_item_all.groupby('model', as_index=False)['quantity_ton'].sum().sort_values('quantity_ton', ascending=False).head(5).rename(columns={'quantity_ton': 'total_quantity_ton'})

      model  total_quantity_ton
5      N220              933.80
6      N330              631.82
0   130-18P              258.45
7      N550              211.00
16  YFP3018              163.79

### Analysis #3: Top 5 Suppliers by Total Purchasing Amount
- Rank suppliers by purchasing amount.
- List top 5 supplier names and total purchasing amount.

In [53]:
df_item_all.groupby('supplier_name', as_index=False)['purchase_total_rmb'].sum().sort_values('purchase_total_rmb', ascending=False).head(5).rename(columns={'purchase_total_rmb': 'total_purchase_rmb'})

                 supplier_name  total_purchase_rmb
14    TriVolt Energy Materials         5518301.034
15  XinAn Industrial Materials         4195506.300
9          IronRiver Materials         3498309.300
2           BraveCore Chemical         3349645.000
17        ZenithRise Chemicals         2782116.000

### Close DB Connection

In [54]:
conn.close()